
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 40;
  public static final int CONST = 15;
  public static final int ENTERO = 17;
  public static final int CASE = 27;
  public static final int COMENTMUL = 46;
  public static final int DOSPT = 9;
  public static final int FOR = 23;
  public static final int AND = 36;
  public static final int IGUAL = 7;
  public static final int OR = 37;
  public static final int CLASS = 11;
  public static final int DIV = 41;
  public static final int UMENOS = 44;
  public static final int IF = 21;
  public static final int LLAIZQ = 2;
  public static final int EOF = 0;
  public static final int PARIZQ = 4;
  public static final int DECIMAL = 18;
  public static final int TRUE = 19;
  public static final int COMENTUNO = 45;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int POTE = 43;
  public static final int CADENA = 16;
  public static final int MENOS = 39;
  public static final int IDENTIFI = 12;
  public static final int MENOR = 34;
  public static final int MOD = 42;
  public static final int REQUIRE = 32;
  public static final int BREAK = 29;
  public static final int SWITCH = 26;
  public static final int MAYOR = 33;
  public static final int LOG = 31;
  public static final int ELSE = 22;
  public static final int PUNTO = 10;
  public static final int WHILE = 24;
  public static final int DEFAULT = 28;
  public static final int LET = 14;
  public static final int PTCOMA = 6;
  public static final int LLADER = 3;
  public static final int DIFER = 35;
  public static final int FALSE = 20;
  public static final int PARDER = 5;
  public static final int VAR = 13;
  public static final int DO = 25;
  public static final int CONSOLE = 30;
  public static final int MAS = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAIZQ",
  "LLADER",
  "PARIZQ",
  "PARDER",
  "PTCOMA",
  "IGUAL",
  "COMA",
  "DOSPT",
  "PUNTO",
  "CLASS",
  "IDENTIFI",
  "VAR",
  "LET",
  "CONST",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "CONSOLE",
  "LOG",
  "REQUIRE",
  "MAYOR",
  "MENOR",
  "DIFER",
  "AND",
  "OR",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "POTE",
  "UMENOS",
  "COMENTUNO",
  "COMENTMUL"
  };
}

