
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresFCA;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GRAFPIE = 27;
  public static final int LLAIZQ = 2;
  public static final int GEREPES = 12;
  public static final int LLADER = 3;
  public static final int DOSPT = 9;
  public static final int CADENA = 30;
  public static final int IGUAL = 18;
  public static final int DOLAR = 11;
  public static final int DECIMAL = 19;
  public static final int PARIZQ = 6;
  public static final int PARDER = 7;
  public static final int PUNESP = 31;
  public static final int VALORES = 24;
  public static final int COMA = 10;
  public static final int COMPARE = 13;
  public static final int EOF = 0;
  public static final int GRAFLIN = 28;
  public static final int IDENTIFI = 15;
  public static final int error = 1;
  public static final int ARCHIVO = 29;
  public static final int CORIZQ = 4;
  public static final int EJEX = 23;
  public static final int GRAFBARRAS = 21;
  public static final int ENTERO = 20;
  public static final int DEFGLOBAL = 14;
  public static final int CORDER = 5;
  public static final int TITULOY = 26;
  public static final int TITULOX = 25;
  public static final int TITULO = 22;
  public static final int STRINGO = 16;
  public static final int DOUBLE = 17;
  public static final int PTCOMA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAIZQ",
  "LLADER",
  "CORIZQ",
  "CORDER",
  "PARIZQ",
  "PARDER",
  "PTCOMA",
  "DOSPT",
  "COMA",
  "DOLAR",
  "GEREPES",
  "COMPARE",
  "DEFGLOBAL",
  "IDENTIFI",
  "STRINGO",
  "DOUBLE",
  "IGUAL",
  "DECIMAL",
  "ENTERO",
  "GRAFBARRAS",
  "TITULO",
  "EJEX",
  "VALORES",
  "TITULOX",
  "TITULOY",
  "GRAFPIE",
  "GRAFLIN",
  "ARCHIVO",
  "CADENA",
  "PUNESP"
  };
}

