
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresFCA;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLADER = 3;
  public static final int GEREPES = 5;
  public static final int PTCOMA = 4;
  public static final int STRINGO = 9;
  public static final int EOF = 0;
  public static final int COMPARE = 6;
  public static final int DOUBLE = 10;
  public static final int IDENTIFI = 8;
  public static final int error = 1;
  public static final int LLAIZQ = 2;
  public static final int DEFGLOBAL = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAIZQ",
  "LLADER",
  "PTCOMA",
  "GEREPES",
  "COMPARE",
  "DEFGLOBAL",
  "IDENTIFI",
  "STRINGO",
  "DOUBLE"
  };
}

