/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vcuch
 */

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class PrincipalW extends javax.swing.JFrame {
    
   

    /**
     * Creates new form PrincipalW
     */

    String textFile ="";
    File archivoEntrada;
    public PrincipalW() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("FIUSAC Copy Analizer");
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/logoIng.jpg"));
        this.setIconImage(ico);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consolaArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        verFile = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirFile = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Ejecutar = new javax.swing.JMenu();
        EjecutarApp = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        ReportToken = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentanaPri.setBackground(new java.awt.Color(204, 204, 204));
        VentanaPri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("CONSOLA");
        VentanaPri.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 160, 60));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setText("E D I T O R");
        VentanaPri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 160, 60));

        consolaArea.setBackground(new java.awt.Color(0, 0, 0));
        consolaArea.setColumns(20);
        consolaArea.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        consolaArea.setForeground(new java.awt.Color(51, 204, 0));
        consolaArea.setRows(5);
        consolaArea.setText("Contenido consola\n....\n...\n..\n.");
        jScrollPane1.setViewportView(consolaArea);

        VentanaPri.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 280, 320));

        verFile.setColumns(20);
        verFile.setRows(5);
        jScrollPane2.setViewportView(verFile);

        VentanaPri.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 380, 320));

        getContentPane().add(VentanaPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));

        jMenu1.setText("Archivo");

        abrirFile.setText("Abrir");
        abrirFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirFileActionPerformed(evt);
            }
        });
        jMenu1.add(abrirFile);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pestaña");

        jMenuItem4.setText("Agregar");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Eliminar");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        Ejecutar.setText("Ejecutar");
        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });

        EjecutarApp.setText("Ejecutar");
        EjecutarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarAppActionPerformed(evt);
            }
        });
        Ejecutar.add(EjecutarApp);

        jMenuBar1.add(Ejecutar);

        jMenu4.setText("Reportes");

        jMenuItem6.setText("Errores");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Estadistico");
        jMenu4.add(jMenuItem7);

        ReportToken.setText("Tokens");
        ReportToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportTokenActionPerformed(evt);
            }
        });
        jMenu4.add(ReportToken);

        jMenuItem9.setText("JSON");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirFileActionPerformed
        JFileChooser JFile = new JFileChooser();
        JFile.showOpenDialog(null);
        File archivo = JFile.getSelectedFile();
        
        
        try{
            FileReader Fread = new FileReader(archivo);
            BufferedReader Bread = new BufferedReader(Fread);
            String texto = "";
            String linea = "";
            
            if(archivo.getName().endsWith("fca")){ // solamente se pueden leer archivos con extension .fca
                while (((linea = Bread.readLine()) != null)){
                    texto += linea+"\n";
                }
                
                
                textFile = texto;
                verFile.setText(texto);
                System.out.println("Contenido del archivo: ");
                System.out.println(textFile);
                JOptionPane.showMessageDialog(null, "Archivo leido");
            } else {
                JOptionPane.showMessageDialog(null, "El archivo no se puede leer");
            }    
        } catch (Exception e){
            
        }   
    }//GEN-LAST:event_abrirFileActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
                // TODO add your handling code here:
                
        
    }//GEN-LAST:event_EjecutarActionPerformed

    private void EjecutarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarAppActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Estoy ejecutando");
        String path = "entrada.txt";
                
        AnalizadoresFCA.Sintactico pars;
        try {
            pars=new AnalizadoresFCA.Sintactico(new AnalizadoresFCA.Lexico(new FileInputStream(path)));
            
            pars.parse();        
        } catch (Exception ex) {
            System.out.println("Error fatal en compilación de entrada.");
            System.out.println("Causa: "+ex.getCause());
        } 
        
        
        
        
        
    }//GEN-LAST:event_EjecutarAppActionPerformed

    private void ReportTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportTokenActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_ReportTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ejecutar;
    private javax.swing.JMenuItem EjecutarApp;
    private javax.swing.JMenuItem ReportToken;
    private javax.swing.JPanel VentanaPri;
    private javax.swing.JMenuItem abrirFile;
    private javax.swing.JTextArea consolaArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea verFile;
    // End of variables declaration//GEN-END:variables
}
